apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springboot-app-ingress
spec:
  rules:
    - http:
        paths:
          - path: /blue
            pathType: Prefix
            backend:
              service:
                name: springboot-app-active
                port:
                  number: 80
          - path: /green
            pathType: Prefix
            backend:
              service:
                name: springboot-app-preview
                port:
                  number: 80
