apiVersion: apps/v1
kind: Deployment
metadata:
 name: the-deployment
 labels:
   deployment: demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        deployment: demo
    spec:
      containers:
      - name: the-container
        image: reachnaveen/springboot-app:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"        
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        volumeMounts:
          - name: config-volume
            mountPath: /config/application.properties
            subPath: application.properties
      volumes:
        - name: config-volume
          configMap:
            name: springboot-app-config
